### PR TITLE
Patch 1= Patch v2.1.0                       

### PR DESCRIPTION
**Pull request by pipX-ux-wizard**

### CODE REVIEW

**Comment by pierre-rouleau** [comment]
@pipX-ux-wizard What are you trying to do here?  Do you know how to use git?  You can sync the 2 repos into the direction of your repo.

**Comment by pipX-ux-wizard** [comment]
trying remove the cloud backdoor of this commit && why do you not care

> There is a backdoor in repo 
> remove bad people in

**Full Changelog**: https://github.com/pipX-ux-wizard/intframework_pip3-My-
# rm
Fork/commits/%F0%9F%AB%A5%F0%9F%9A%AA

**Comment by pipX-ux-wizard** [comment]
Not every one in the same

**Comment by pipX-ux-wizard** [comment]
@pierre-rouleau pierre-rouleau

Not every one in the same

**Comment by pipX-ux-wizard** [comment]
If developers didn't make things so wishy washed and confusing I've been practicing

**Review by pipX-ux-wizard — COMMENTED** [review]
I don't need to perm to copy && edit forked repo

**Pull request closed without merging**
